version: 0.1.0.{build}

shallow_clone: true

environment:
  matrix:
  - LUA_VER: 5.1
  - LUA_VER: 5.2
  - LUA_VER: 5.3
  - LUA_VER: luajit-2.0
  - LUA_VER: luajit-2.1

install:
  - appveyor DownloadFile https://dl.bintray.com/xpol/luavm/LuaVM-0.4.0-vs2015-x64.exe -FileName LuaVM-vs2015-x64.exe
  - LuaVM-vs2015-x64.exe /verysilent
  - set PATH=%LocalAppData%\LuaVM;%PATH%

before_build:
  - luavm use %LUA_VER%
  - where luavm
  - where luarocks
  - luarocks install luafilesystem

build_script:
  - luarocks make

before_test:
  - luarocks install busted

test_script:
  - busted
